# Change these first
owner: thingpress # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Branza
    url: https://thing.press/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.thing.press
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: System Status
  introTitle: "**thing.press**"
  introMessage: System status is compiled using **real-time** data processed by our [GitHub repository](https://github.com/thingpress/status) and automated workflows.
  navbar:
    - title: thing.press System Status
      href: /
    - title: My Account
      href: https://my.thing.press/
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
