# Change these first
owner: thingpress # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Branza
    url: https://thing.press/
  - name: Dashboard
    url: https://my.thing.press/
  - name: Projects
    url: https://projects.thing.press/
  - name: Honey
    url: https://honey.thing.press/
  - name: Latte
    url: https://latte.thing.press/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.thing.press
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/thingpress/status/master/assets/thing.press-sq.png
  name: thing.press
  introTitle: "**Network Status**"
  introMessage: Metrics are compiled using **real-time** data processed by our [GitHub repository](https://github.com/thingpress/status) and automated workflows.
  links:
    - rel: stylesheet
      href: https://raw.githubusercontent.com/thingpress/status/master/assets/styles.css
  navbar:
    - title: Dashboard
      href: https://my.thing.press/
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
